### ISSUE TITLE
Tmux support?

### ISSUE THREAD

**Issue by jgc37** [petobens/trueline#10]
In tmux it shows up as a couple of underscores.  Don't know if this is a problem with tmux or trueline.

**Comment by petobens** [comment]
I'm using it under tmux just fine. Could please post your configs (bashrc / tmux.conf) and some screenshot in order for me to reproduce your behavior? Thanks!

**Comment by jgc37** [comment]
Sorry for the late response 

Here is my tmux.conf

**Comment by jgc37** [comment]
Problem was solved by starting tmux with tmux -u

**Comment by petobens** [comment]
Glad you sorted it out.
