### ISSUE TITLE
vi mode segment at the end of the prompt

### ISSUE THREAD

**Issue by micalexander** [petobens/trueline#12]
I attempted to modify your code/add a custom segment in order to have a vi mode segment at the end so the color would change when in insert mode and command mode respectively.

Desired behavior:

![image](https://user-images.githubusercontent.com/1943736/64355875-cf465000-cfb6-11e9-9691-10db5b162079.png)

![image](https://user-images.githubusercontent.com/1943736/64356003-ff8dee80-cfb6-11e9-9d3f-8ad54234e609.png)

I couldn't seem to find where you were detecting if you were in insert or command mode.

Anything you do to point me in the right direction to accomplishing this affect would be greatly appreciated.

**Comment by petobens** [comment]
I think this is not possible at the moment. I'm using `show-mode-in-prompt` to render the vi segment. 
From the `readline` man page:
```
       show-mode-in-prompt (Off)
              If set to On, add a string to the beginning of the prompt indicating the editing mode: emacs, vi command, or vi insertion.  The mode strings are user-settable (e.g., emacs-mode-string).
```
So apparently we can only modify the appearance of the segment but not its position.

**Comment by micalexander** [comment]
Ok, that makes sense. I should've looked at the man page, thanks for the reply.
