### ISSUE TITLE
Add font style as a variable.

### ISSUE THREAD

**Issue by micalexander** [petobens/trueline#13]
It seems that you have the segments set to normal as default. It would be nice to pass that as a variable as below:

```
declare -a TRUELINE_SEGMENTS=(
  'user,grey,special_grey,bold'
  'working_dir,mono,cursor_grey,bold'
  'git,grey,special_grey,bold'
)
```

**Comment by petobens** [comment]
Good idea. I'll try to write something up over the weekend (a pr is obviously welcome though).

**Comment by petobens** [comment]
Sorry about the delay. Could you please try #14? Thanks
