### ISSUE TITLE
Add instructions for installing Nerd Fonts Source Code Pro in Ubuntu

### ISSUE THREAD

**Issue by juanpampliega** [petobens/trueline#15]
This worked for me

```bash
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/SourceCodePro.zip
mkdir ~/.fonts
unzip SourceCodePro.zip -d ~/.fonts
```

**Comment by petobens** [comment]
I don't want to add a distro-specific section to the readme. Besides nerd font's repo installation steps seem clear enough (and now we'll always also have this issue as a reference). Closing
