### ISSUE TITLE
Root has issue using trueline

### ISSUE THREAD

**Issue by Mte90** [petobens/trueline#16]
![Screenshot_20191005_222044](https://user-images.githubusercontent.com/403283/66260407-81438880-e7be-11e9-90a2-1a79a3055cd9.png)
As you can see in the screen with the root user I get the normal user showed but the color is different. Maybe because I am loading the sh file from the home of the mte90 user?
Also I don't know why I get `130` very often as root, maybe is a PID?

**Comment by petobens** [comment]
Is `mte90` a root user? Try running `echo ${EUID}` and see what you get.  Also can you please provide the exacts steps to reproduce your issue? Thanks

Regarding the 130 error code that generally indicates that command received a SIGINT... steps for me to reproduce this are also desirable here.

**Comment by Mte90** [comment]
No mte90 is not the root user.
That line is from the root user but the trueline file is loaded by the home folder of my user (to avoid duplicates).
With the user everything is fine but with root I have this problem.

**Comment by petobens** [comment]
Can you post the exacts steps for me to reproduce this behaviour? Thanks

**Comment by Mte90** [comment]
Investigate a bit, on this line `is_root` is true https://github.com/petobens/trueline/blob/master/trueline.sh#L74 but the next if is not executed.
Seems that on my system the variable `$USER` is always the basic user (in my case mte90). Maybe because to became root I usually do a `su` from the `mte90` user?

**Comment by Mte90** [comment]
About the exit_status I didn't know that was that. I will customize the segments variable to not print it :-)

**Comment by petobens** [comment]
I stand with my previous comment. Closing now.
