### ISSUE TITLE
The icons are so small

### ISSUE THREAD

**Issue by GLPG35** [petobens/trueline#19]
I'm running Tilix terminal in Arch Linux and the icons look so small compared to your preview.

![Terminal](https://user-images.githubusercontent.com/55563130/73144574-eda40980-4085-11ea-9643-5f0987f43112.png)

My .bashrc file:

```
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$'

neofetch | lolcat

declare -A TRUELINE_COLORS=(
    [light_blue]='75;161;207'
    [grey]='99;99;100'
    [pink]='199;88;157'
)

declare -a TRUELINE_SEGMENTS=(
    'working_dir,light_blue,black,normal'
    'git,grey,black,normal'
    'newline,pink,black,bold'
)

declare -a TRUELINE_SEGMENTS=(
    'working_dir,mono,cursor_grey,normal'
    'git,grey,special_grey,normal'
    'newline,black,orange,bold'
)

declare -A TRUELINE_SYMBOLS=(
    [segment_symbol_name]='|' # actual symbol
)

source ~/trueline/trueline.sh
```

My font is 'Nerd Font Source Code Pro'

**Comment by petobens** [comment]
Try playing with the font size and see if the issue continues... I've seen this before (https://github.com/petobens/trueline/issues/11). To check whether this is specific to trueline  (which I don't think it is) see about inputing the symbol in your terminal and check the symbol size (my guess is that it's also small).

**Comment by GLPG35** [comment]
I tried changing the font size in the profile settings on tilix. I changed the font size but the icon is still small. I searched about why the icons look so small but nobody has an answer yet :/

**Comment by petobens** [comment]
Is it small also outside trueline? Try opening vim, enter insert mode (by pressing i) and type `Ctrl-Vuf015` and check the resulting home dir icon font size. If it's also small then it is not something related to trueline but rather to your terminal font size config.

**Comment by GLPG35** [comment]
I changed the font in terminal to another Source Code Pro and it works, now the icons look very well. Thanks for ur help

**Comment by petobens** [comment]
Glad it got sorted out.
