### ISSUE TITLE
Problem with visualization or encoding

### ISSUE THREAD

**Issue by juancebarberis** [petobens/trueline#20]
Hi! 
I just installed trueline and see there is a problem with the encoding. Don't know if I need to download some extensions or something to make it works.

[https://i.imgur.com/FAZjSVh.png](url)

**Comment by petobens** [comment]
Hi. The link seems to be broken so there is no way for me to fix this unless I get a clear picture of what's going on. Please give a detailed explanation of the problem (with a proper screenshot). Thanks

**Comment by juancebarberis** [comment]
Sorry for that. Here's the image.
[Img](https://i.imgur.com/FAZjSVh.png)

**Comment by petobens** [comment]
Seems to be a font problem. Did you install nerd fonts as mentioned in the readme? Once you do that then you also need to tell your terminal to use them (I think that should fix it).

**Comment by juancebarberis** [comment]
Thanks!!! I didn't read that. 

btw, buen trabajo che!
