### ISSUE TITLE
segment separator outlines are visible around each segments in bright colors

### ISSUE THREAD

**Issue by Davidportlouis** [petobens/trueline#22]
there is a thin blue line around user name segment and a thin red line around the error code segment.
![Screenshot from 2020-07-29 13-38-18](https://user-images.githubusercontent.com/18904157/88774691-5f7a1e80-d1a1-11ea-9eed-ee0b0b22f647.png)

**Comment by NickLarsenNZ** [comment]
I installed `gnome-tweaks` and set the following:

- Fonts
  - Hinting: None
   - Antialiasing: Standard (grayscale)

**Comment by StarrKiss** [comment]
I am getting this too despite having hinting set as none in KDE plasma.

**Comment by petobens** [comment]
Seems to be a duplicate of https://github.com/petobens/trueline/issues/5. I don't believe there's much that I can do to help with this since it seems to be a font/terminal problem. Let's keep it open though

**Comment by Davidportlouis** [comment]
@NickLarsenNZ  Solution seems to rectify the ugly segment outline problem, seems like nerd fonts has some issue with subpixel anti aliasing and it is fixed by @NickLarsenNZ gnome-tweak solution. So I'm Closing this issue.
Thanks @NickLarsenNZ  @petobens

**Comment by NickLarsenNZ** [comment]
For what its worth, I've switched to Alacritty terminal and haven't had any problems with fonts and aliasing.

https://github.com/alacritty/alacritty

**Comment by petobens** [comment]
That's a good call. I use alacritty and kitty and they both seem to work fine with fonts/aliasing.
