### ISSUE TITLE
What is with the (130) number that appear when I press Ctrl+C and how to disable it

### ISSUE THREAD

**Issue by cpuuntery** [petobens/trueline#26]
When I press Ctrl+C. I get red arrow with number the 130 inside it. this weird number annoy me. how to disable that behaviour. Also, sometime I get other weird numbers like 10 or 1. I want to disable them too

**Comment by petobens** [comment]
That's the `exit_status` segment: https://github.com/petobens/trueline#segments

You can define your own custom segment list as in that link or simply comment out the exit_status segment from the default segment list: https://github.com/petobens/trueline/blob/c9f93a8c47835ba7f10e1223203dd03fdb97b456/trueline.sh#L431
