### ISSUE TITLE
Support symbol for exit status

### ISSUE THREAD

**Issue by LiteracyFanatic** [petobens/trueline#30]
It'd be great if it was possible to add a symbol for the exit status. Pureline sets it to U+2691 : BLACK FLAG by default.

**Comment by petobens** [comment]
Implemented. It is empty by default so if you want to add the symbol you need to add something like the following to your config:
```bash
declare -A TRUELINE_SYMBOLS=([exit_status]=' ')
```

**Comment by LiteracyFanatic** [comment]
Thanks!
