### ISSUE TITLE
Strange Default Symbols

### ISSUE THREAD

**Issue by Acry** [petobens/trueline#35]
Hey there,

most of the default Symbols are broken on my system. Can anyone help?

![image](https://user-images.githubusercontent.com/3709175/112356487-f23a7100-8cce-11eb-9aab-cd7b640427e3.png)

**Comment by petobens** [comment]
Hi! What terminal emulator are you using? Did you install nerd fonts?

**Comment by Acry** [comment]
Hi!
Yeah must be the missing nerd font.
The screenshot is from gedit, but all my terminal emulators and vscode showing the same. Actually I had a clue after reading the proper readme section. Maybe you want to point it more out, that one needs the nerd font? 
However, ty for your good work. I am enjoying it.

**Comment by petobens** [comment]
Glad you fixed it.
