### ISSUE TITLE
Icons do not have a transparent background

### ISSUE THREAD

**Issue by heyyzoeyy** [petobens/trueline#4]
![image88](https://user-images.githubusercontent.com/43478986/59791586-5f370080-92ca-11e9-807a-b18057f9debe.png)
Any solution to fix this?

**Comment by petobens** [comment]
I'm afraid I don't follow: could you please elaborate a bit more / show your config? Thanks

**Comment by heyyzoeyy** [comment]
Ah sorry, any `[segment_separator]` icon does not have the same background as the terminal. In the `.bashrc` file, it only has `source ~/.trueline/trueline.sh`. If I add `declare -A TRUELINE_SYMBOLS=( [segment_separator]=''`, (that triangle) it is the same. Basically, it does not look like the screenshot on the README where the triangle is connected to a block.

**Comment by petobens** [comment]
Can you post your full config so I can see precisely what you are trying to achieve?

**Comment by heyyzoeyy** [comment]
Never mind! I have experimented and I have changed in the trueline.sh these lines
```
#---------------+
# Configuration |
#---------------+
if [[ "${#TRUELINE_COLORS[@]}" -eq 0 ]]; then
    declare -A TRUELINE_COLORS=(
        [black]='36;39;46' #24272e
        [cursor_grey]='40;44;52' #282c34
        [default]='36;39;46' #24272e
        [green]='152;195;121' #98c379
        [grey]='171;178;191' #abb2bf
        [light_blue]='97;175;239' #61afef
        [mono]='130;137;151' #828997
        [orange]='209;154;102' #d19a66
        [purple]='198;120;221' #c678dd
        [red]='224;108;117' #e06c75
        [special_grey]='59;64;72' #3b4048
        [white]='208;208;208' #d0d0d0
    )
fi
```
to
```
#---------------+
# Configuration |
#---------------+
if [[ "${#TRUELINE_COLORS[@]}" -eq 0 ]]; then
    declare -A TRUELINE_COLORS=(
        [black]='36;39;46' #24272e
        [cursor_grey]='40;44;52' #282c34
#        [default]='36;39;46' #24272e
        [green]='152;195;121' #98c379
        [grey]='171;178;191' #abb2bf
        [light_blue]='97;175;239' #61afef
        [mono]='130;137;151' #828997
        [orange]='209;154;102' #d19a66
        [purple]='198;120;221' #c678dd
        [red]='224;108;117' #e06c75
        [special_grey]='59;64;72' #3b4048
        [white]='208;208;208' #d0d0d0
    )
fi
```
(commented out default)

Now, it looks like this
![image168](https://user-images.githubusercontent.com/43478986/59864347-84854680-937e-11e9-9652-4eb30e431c46.png)

**Comment by petobens** [comment]
Ok, glad you sorted it out yourself (since I cannot still figure what's your desired output).
For the record you can change the stock colors without modifying the source code (see the configuration section in the readme).
