### ISSUE TITLE
Weird behaviour on gnome-terminal(Solus Linux) There is an ungly outline

### ISSUE THREAD

**Issue by cata0309** [petobens/trueline#5]
![Screenshot from 2019-06-20 17-04-16](https://user-images.githubusercontent.com/35623921/59855396-931f2e00-937d-11e9-8282-a76521098168.png)
The orange outline square. How do I get rid of it ?

**Comment by petobens** [comment]
Are you using the default settings? Did you try this in another terminal? (i.e is it gnome specific?)

**Comment by cata0309** [comment]
I am using the default settings, I will install tilix now and see

**Comment by cata0309** [comment]
It has the same behavior on tilix, tilda, and it's behavior tend to become worse:
in tilda:
![image](https://user-images.githubusercontent.com/35623921/59869086-287ceb00-939b-11e9-813a-6714d8a9af1a.png)

**Comment by cata0309** [comment]
I am using furacode from nerd fonts

**Comment by cata0309** [comment]
It appears to happen with any font I try

**Comment by petobens** [comment]
Ok, I'll try to reproduce it myself (I don't see such behaviour in my alacritty terminal) and try to fix it. Thanks for the report

**Comment by cata0309** [comment]
No problem, I will help with testing

**Comment by petobens** [comment]
I can reproduce this with tilda (but since it seems to be a terminal-specific thing it might take me a while to fix it)

**Comment by cata0309** [comment]
I am using gnome-terminal on Solus, that was my main bug

**Comment by cata0309** [comment]
Is all the font's fault. The issue is with the font, not with trueline. The nerd fonts have some weird spacing problems, I tried with other fonts and everything was fine, so I am closing the issue

**Comment by petobens** [comment]
Thanks for the info and for tracking this down.

**Comment by cata0309** [comment]
You welcome, I love to contribute to FOSS projects!

**Comment by Davidportlouis** [comment]
@cata0309  what font did you use to fix this issue ?

**Comment by cata0309** [comment]
I will have another check as I stopped using trueline and I will tell you ?
