### ISSUE TITLE
OSX / Iterm2 Issue

### ISSUE THREAD

**Issue by erzz** [petobens/trueline#8]
Added the following to .bash_profile 

```
# Trueline enable
source ~/trueline/trueline.sh
```

and get the following:

```
Last login: Tue Jun 25 10:03:52 on ttys005
-bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
-bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

**Comment by petobens** [comment]
Associative arrays were added to bash in version 4.0 (in 2010). What version are you using? You might need to upgrade it.

**Comment by petobens** [comment]
As I said in my previous comment I'm pretty sure this is related to the bash version. I'm closing now. If you cannot fix this by updating bash please let me know and I'll reopen.

**Comment by Nicholas-Autio-Mitchell** [comment]
@petobens  I am seeing the above error on Mac OSX using bash version 5.2.15.

Any ideas what the issue could be?
