### ISSUE TITLE
Transparent background terminals

### ISSUE THREAD

**Issue by coderkalyan** [petobens/trueline#9]
I am using bash on a terminal with a semi transparent black background using compton. Unfortunately trueline still uses the $default background to the last character in the prompt, causing it to render opaque. As $default only accepts RGB and no alpha, I am not sure how to solve this.
![2019-07-03-040223_233x113_scrot](https://user-images.githubusercontent.com/35181624/60551002-81f3fb00-9d47-11e9-931a-92fcc61e9c3a.png)

**Comment by petobens** [comment]
Thanks for the report. I'll take a look during the weekend (I don't know if there is straightforward way of achieving this though)

**Comment by petobens** [comment]
Please try my latest commit. Let me know if it fixes your issue.

**Comment by coderkalyan** [comment]
It appears that it does indeed. Thanks a lot!
